yurutomo/accounts/urls.py
# from django.contrib import admin
from django.urls import path


from . import views


app_name = 'accounts'


urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('guestlogin/', views.GuestLogin.as_view(), name='guest_login'),
    path('settings/<uuid:pk>', views.ChangeSettingsView.as_view(), name='settings'),
    path('profile/<uuid:pk>', views.ProfileUpdateView.as_view(), name='profile_settings'),
]

yurutomo/chatrooms/urls.py
from django.urls import path

from . import views

app_name= 'chatrooms'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('room-match', views.RoomMatchView.as_view(), name='room_match'),
    path('room/<uuid:pk>', views.RoomView.as_view(), name='room'),
    path('skyway', views.skyway, name='skyway'),
    path('rooms', views.RoomListView.as_view(), name='room_list'),

    path('api/populartopics', views.popular_topics, name='popular_topics'),
    path('api/searchtopics', views.search_topics, name='search_topics'),
    path('api/createtopic', views.create_topic, name='create_topic'),

    path('api/registermatching', views.register_matching, name='register_matching'),
    path('api/unregistermatching', views.unregister_matching, name='unregister_matching'),
    path('api/getmatchroom', views.get_match_room, name='get_match_room'),
    path('api/confirmmatching', views.confirm_matching, name='confirm_matching'),
    path('api/cancelconfirm', views.cancel_confirm, name='cancel_confirm'),
    path('api/getmatchcompleted', views.get_match_completed, name='get_match_completed'),
]

yurutomo/yurutomo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# adminsite のサイドバーを無効にする
admin.site.enable_nav_sidebar = False

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chatrooms.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

yurutomo/accounts/models.py
""" Account model """
from uuid import uuid4
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
from django.core.mail import send_mail
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.contrib.auth.validators import UnicodeUsernameValidator
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill


# Default user icon image ( /media/DEFAULT_USER_ICON_IMAGE )
DEFAULT_USER_ICON_IMAGE = 'default-user-icon.png'

def _user_icon_image_upload_to(instance, filename):
    path = settings.USER_ICON_UPLOAD_DIR
    ext = str(filename).split('.')[-1]
    name = str(uuid4()) + '.' + ext
    return '{}/{}'.format(path, name)

# Create your models here.
class UserManager(BaseUserManager):
    """ User manager """
    use_in_migrations = True

    def _create_user(self, username, password, **extra_fields):
        username = self.model.normalize_username(username)
        user = self.model(username=username, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(username, password, **extra_fields)

    def create_superuser(self, username, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(username, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """ User model """
    username_validator = UnicodeUsernameValidator()

    uuid = models.UUIDField(primary_key=True, default=uuid4, editable=False)

    username = models.CharField(
        _('username'),
        max_length=20,
        unique=True,
        validators=[username_validator],
    )

    icon_image = ProcessedImageField(
        upload_to=_user_icon_image_upload_to,
        processors=[ResizeToFill(200, 200)],
        format='JPEG',
        options={'quality': 60},
        default=DEFAULT_USER_ICON_IMAGE
    )

    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
    )
    is_guest = models.BooleanField(
        _('guest'),
        default=False,
    )

    reg_date = models.DateTimeField(_('registration date'), default=timezone.now)

    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

yurutomo/accounts/forms.py
""" Account form """
from django.contrib.auth.forms import (
    UserCreationForm, UsernameField, UserChangeForm, AuthenticationForm)
from django.forms.models import ModelForm
from django.forms import (
    CharField, TextInput, PasswordInput)


from .models import User


class UserCreateForm(UserCreationForm):
    """ User creatino form """
    password1 = CharField(max_length=50, min_length=6, widget=PasswordInput)

    class Meta:
        model = User
        fields = ('username',)
        field_classes = {
            'username': UsernameField,
        }
        widgets = {
            'username': TextInput(attrs={'id': 'id_username'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        del self.fields['password2']
        self.fields['username'].label = 'ユーザー名'
        self.fields['username'].widget.attrs['class'] = 'uk-input uk-form-width-large'
        self.fields['password1'].label = 'パスワード'
        self.fields['password1'].widget.attrs['class'] = 'uk-input uk-form-width-large'
        self.fields['password1'].help_text = 'パスワードは6文字以上'


class LoginForm(AuthenticationForm):
    """ Login form """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'ユーザー名'
        self.fields['username'].widget.attrs['class'] = 'uk-input uk-form-width-large'
        self.fields['username'].widget.attrs['placeholder'] = 'ユーザー名'
        self.fields['password'].label = 'パスワード'
        self.fields['password'].widget.attrs['class'] = 'uk-input uk-form-width-large'
        self.fields['password'].widget.attrs['placeholder'] = 'パスワード'

    def non_field_errors(self):
        error_messages = super().non_field_errors()
        if error_messages:
            error_messages[0] = 'Incorrect Username or Password'
        return error_messages


class CustomUserChangeForm(UserChangeForm):
    """ User settings change form """
    password = None

    class Meta:
        model = User
        fields = ('username',)
        field_classes = {
            'username': UsernameField,
        }
        widgets = {
            'username': TextInput(attrs={'id': 'id_username'}),
        }


class ProfileForm(ModelForm):
    """ Profile settings form """
    class Meta:
        model = User
        fields = ('username', 'icon_image')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'ユーザー名'
        self.fields['username'].widget.attrs['class'] = 'uk-input uk-form-width-large'
        self.fields['icon_image'].label = 'プロフィール画像'

yurutomo/accounts/views.py
""" Account views """
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.views import generic
from django.core.signing import dumps, loads, SignatureExpired, BadSignature
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model, login
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.sites.shortcuts import get_current_site
from django.views import generic
from django.template.loader import render_to_string
from django.utils.crypto import get_random_string


from .forms import UserCreateForm, LoginForm, CustomUserChangeForm, ProfileForm


User = get_user_model()


# Create your views here.
class SignUpView(generic.CreateView):
    """
    User creation view
    """
    form_class = UserCreateForm
    template_name = 'accounts/signup.html'
    success_url = reverse_lazy('chatrooms:room_match')

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        self.object = user
        return HttpResponseRedirect(self.get_success_url())
    
    def form_invalid(self, form):
        return super().form_invalid(form)


class Login(LoginView):
    """ Login view"""
    form_class = LoginForm
    template_name = 'accounts/login.html'

    def form_valid(self, form):
        user = form.get_user()
        if user.is_guest:
            # ゲストユーザーではログインさせない
            return HttpResponseRedirect(reverse_lazy('accounts:login'))
        
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        next_path = self.request.GET.get('next')
        if next_path is not None:
            context['next_path'] = next_path
        return context


class Logout(LoginRequiredMixin, LogoutView):
    """Logout view"""
    pass


class GuestLogin(generic.RedirectView):
    url = reverse_lazy('chatrooms:room_match')
    
    def get(self, request):
        # ゲストログイン
        user, created = User.objects.update_or_create(
            username='guest-'+ get_random_string(12),
            password='',
            is_guest=True,
        )
        user.save()
        login(self.request, user)
        self.object = user

        return super().get(request)
    
    def get_redirect_url(self, *args, **kwargs):
        # nextパラメータがあれば、それにリダイレクト
        next_path = self.request.GET.get('next')
        if next_path:
            return next_path
        return super().get_redirect_url(*args, **kwargs)


class ChangeSettingsView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    """ Change user settings view"""
    login_url = reverse_lazy('accounts:login')
    model = User
    form_class = CustomUserChangeForm
    template_name = 'accounts/settings.html'

    def test_func(self):
        current_user = self.request.user
        page_user = get_object_or_404(self.model, pk=self.kwargs['pk'])
        return current_user.pk == page_user.pk or current_user.is_superuser

    def get_success_url(self):
        return reverse_lazy('chatrooms:index')

    def form_valid(self, form):
        messages.success(self.request, '正常に更新されました')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.warning(self.request, '更新に失敗しました')
        return super().form_invalid(form)


class ProfileUpdateView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    """ Change user profile view """
    login_url = reverse_lazy('accounts:login')
    model = User
    form_class = ProfileForm
    template_name = 'accounts/profile_settings.html'

    def test_func(self):
        current_user = self.request.user
        page_user = get_object_or_404(self.model, pk=self.kwargs['pk'])
        return current_user.pk == page_user.pk or current_user.is_superuser

    def get_success_url(self):
        return reverse_lazy('accounts:profile_settings', kwargs={'pk': self.request.user.pk})

    def form_valid(self, form):
        messages.success(self.request, '正常に更新されました')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.warning(self.request, '更新に失敗しました')
        return super().form_invalid(form)

yurutomo/accounts/templates/accounts/logged_out.html
{% extends 'base.html' %} 

{% block content %}
<a href="{% url 'chatrooms:index' %}"><button class="btn"> TOP</button> </a>
{% endblock %}

yurutomo/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}ログイン｜ゆるとも{% endblock %}


{% block content %}
<!-- <h1>Here is Login form </h1> -->
<div class="uk-section" uk-height-viewport>
    <div class="uk-width-1-1">
        <div class="uk-container">
            <div class="uk-grid-margin uk-grid uk-grid-stack" uk-grid>
                <div class="uk-width-1-1@m">
                    <div class="uk-flex uk-flex-center">
                        {% if form.non_field_errors %}
                        {% for error in form.non_field_errors %}
                        <div class="uk-alert-warning uk-width-large" uk-alert>
                            <a class="uk-alert-close" uk-close></a>
                            <p>{{ error }}</p>
                        </div>
                        {% endfor %}
                        {% endif %}

                        {% if form.errors %}
                        {% for field in form %}
                        {%for error in field.errors %}
                        <div class="uk-alert-warning uk-width-large" uk-alert>
                            <a class="uk-alert-close" uk-close></a>
                            <p>{{ error }}</p>
                        </div>
                        {% endfor %}
                        {% endfor %}
                        {% endif %}
                    </div>
                    <div
                        class="uk-margin uk-width-large uk-margin-auto uk-card uk-card-default uk-card-body uk-box-shadow-large">
                        <h3 class="uk-card-title uk-text-center">ログイン</h3>
                        <form method="post">
                            {% csrf_token %}
                            <div class="uk-margin">
                                <div class="uk-inline uk-width-1-1">
                                    <span class="uk-form-icon" uk-icon="icon: user"></span>
                                    {{form.username}}
                                </div>
                            </div>
                            <div class="uk-margin">
                                <div class="uk-inline uk-width-1-1">
                                    <span class="uk-form-icon" uk-icon="icon: lock"></span>
                                    {{form.password}}
                                </div>
                            </div>
                            <div class="uk-margin">
                                <button class="uk-button uk-button-primary uk-button-large uk-width-1-1"
                                    type="submit">ログイン</button>
                            </div>
                            <div class="uk-text-small uk-text-center">
                                新規登録は<a href="{% url 'accounts:signup' %}">こちら</a>
                            </div>

                            <div class="uk-margin">
                                <a href="{% url 'accounts:guest_login' %}?next={{next_path}}" class="uk-button uk-button-secondary uk-button-large uk-width-1-1">
                                    登録せずにはじめる
                                </a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

yurutomo/accounts/templates/accounts/profile_settings.html
{% extends 'base.html' %}

{% block content %}
<div class="uk-container uk-margin-large-top">
    <div class="uk-width-1-1@m">
        <div>
            <h2 class="uk-text-center">プロフィール編集</h3>
        </div>
    </div>
    <div class="uk-width-1-1@m">
        <div class="uk-flex uk-flex-center">
            <div class="uk-flex uk-flex-column">
                {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                <div class="uk-alert-warning uk-width-large" uk-alert>
                    <a class="uk-alert-close" uk-close></a>
                    <p>{{ error }}</p>
                </div>
                {% endfor %}
                {% endif %}

                {% if form.errors %}
                {% for field in form %}
                {%for error in field.errors %}
                <div class="uk-alert-warning uk-width-large" uk-alert>
                    <a class="uk-alert-close" uk-close></a>
                    <p>{{ error }}</p>
                </div>
                {% endfor %}
                {% endfor %}
                {% endif %}
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="uk-margin">
                        <label class="uk-form-label uk-text-large">{{form.username.label}}</label>
                        <div class="uk-margin-small uk-width-1-1 uk-text-center">
                            {{form.username}}
                        </div>
                    </div>
                    <div class="uk-margin">
                        <label class="uk-form-label uk-text-large">{{form.icon_image.label}}</label>
                        <div class="uk-margin-small uk-width-1-1 uk-text-center">
                            <img class="uk-width-medium" src="{{ user.icon_image.url }}" alt="user_icon_image">

                        </div>
                        <div class="uk-margin-small uk-width-1-1 uk-text-center">
                            {{form.icon_image}}
                        </div>
                    </div>
                    <div class="uk-margin-large-top">
                        <button class="uk-button uk-button-primary" type="submit">Save</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

yurutomo/accounts/templates/accounts/settings.html
{% extends 'base.html' %}


{% block content %}

<div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}
        {% for field in form %}
        <div class="row">
            <div class="field">
                {{ field.label }}
            </div>
            <div class="field">
                {{ field }}
            </div>
            <div class="field">
                {% if field.help_text %}
                <span class="field_help_text">{{ field.help_text}}</span>
                {% endif %}
            </div>
            <div class="field">
                {{ field.errors }}
            </div>
        </div>
        {% endfor %}

        <div class="row">
            <div class=""><button type="submit" class="btn">Confirm</button></div>
        </div>
    </form>
</div>

{% endblock %}

yurutomo/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block title %}新規登録｜ゆるとも{% endblock %}

{% block content %}
<div class="uk-section" uk-height-viewport>
    <div class="uk-width-1-1">
        <div class="uk-container">
            <div class="uk-grid-margin uk-grid uk-grid-stack" uk-grid>
                <div class="uk-width-1-1@m">
                    <div class="uk-flex uk-flex-center">
                        {% if form.non_field_errors %}
                        {% for error in form.non_field_errors %}
                        <div class="uk-alert-warning uk-width-large" uk-alert>
                            <a class="uk-alert-close" uk-close></a>
                            <p>{{ error }}</p>
                        </div>
                        {% endfor %}
                        {% endif %}

                        {% if form.errors %}
                        {% for field in form %}
                        {%for error in field.errors %}
                        <div class="uk-alert-warning uk-width-large" uk-alert>
                            <a class="uk-alert-close" uk-close></a>
                            <p>{{ error }}</p>
                        </div>
                        {% endfor %}
                        {% endfor %}
                        {% endif %}
                    </div>

                    <div
                        class="uk-margin uk-width-large uk-margin-auto uk-card uk-card-default uk-card-body uk-box-shadow-large">
                        <h3 class="uk-card-title uk-text-center">新規登録</h3>
                        <form method="post">
                            {% csrf_token %}
                            <div class="uk-margin">
                                <label class="uk-form-label">{{form.username.label}}</label>
                                <div class="uk-inline uk-width-1-1">
                                    {{form.username}}
                                </div>
                            </div>
                            <div class="uk-margin">
                                <label class="uk-form-label">{{form.password1.label}}</label>
                                <div class="uk-inline uk-width-1-1">
                                    {{form.password1}}
                                </div>
                                <div class="uk-text-small uk-text-right">
                                    <p>{{form.password1.help_text}}</p>
                                </div>
                            </div>
                            <div class="uk-margin">
                                <button class="uk-button uk-button-primary uk-button-large uk-width-1-1"
                                    type="submit">登録</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}