yurutomo/accounts/urls.py
# from django.contrib import admin
from django.urls import path


from . import views


app_name = 'accounts'


urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('guestlogin/', views.GuestLogin.as_view(), name='guest_login'),
    path('settings/<uuid:pk>', views.ChangeSettingsView.as_view(), name='settings'),
    path('profile/<uuid:pk>', views.ProfileUpdateView.as_view(), name='profile_settings'),
]

yurutomo/chatrooms/urls.py
from django.urls import path

from . import views

app_name= 'chatrooms'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('room-match', views.RoomMatchView.as_view(), name='room_match'),
    path('room/<uuid:pk>', views.RoomView.as_view(), name='room'),
    path('skyway', views.skyway, name='skyway'),
    path('rooms', views.RoomListView.as_view(), name='room_list'),

    path('api/populartopics', views.popular_topics, name='popular_topics'),
    path('api/searchtopics', views.search_topics, name='search_topics'),
    path('api/createtopic', views.create_topic, name='create_topic'),

    path('api/registermatching', views.register_matching, name='register_matching'),
    path('api/unregistermatching', views.unregister_matching, name='unregister_matching'),
    path('api/getmatchroom', views.get_match_room, name='get_match_room'),
    path('api/confirmmatching', views.confirm_matching, name='confirm_matching'),
    path('api/cancelconfirm', views.cancel_confirm, name='cancel_confirm'),
    path('api/getmatchcompleted', views.get_match_completed, name='get_match_completed'),
]

yurutomo/yurutomo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# adminsite のサイドバーを無効にする
admin.site.enable_nav_sidebar = False

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chatrooms.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

yurutomo/chatrooms/models.py
from uuid import uuid4
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth import get_user_model


User = get_user_model()

# Create your models here.

class Tag(models.Model):
    name = models.CharField(_('tag name'), max_length=255)
    
    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.full_clean()
        super().save(*args, **kwargs)
    
    def clean(self):
        """
        name から空白をなくす
        """
        if self.name:
            self.name = "".join(self.name.split())

class Topic(models.Model):
    name = models.CharField(_('topic name'), max_length=255)
    number = models.IntegerField(_('number'), default=2)
    tags = models.ManyToManyField(Tag, blank=True)

    def __str__(self):
        return self.name
    
    def data(self):
        d = {
            "name": self.name,
            "number": self.number
        }
        return d
    
    def save(self, *args, **kwargs):
        self.full_clean()
        super().save(*args, **kwargs)
    
    def clean(self):
        """
        name から空白をなくす
        """
        if self.name:
            self.name = "".join(self.name.split())

class Room(models.Model):
    uuid = models.UUIDField(primary_key=True, default=uuid4, editable=False)

    users = models.ManyToManyField(User)

    created_date = models.DateTimeField(_('created date'), default=timezone.now)

    is_active = models.BooleanField(_('active'), default=False)


class MatchingRecord(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, null=True)
    number = models.IntegerField(_('number of users'), default=2)
    submission_time = models.DateTimeField(_('submission time'), default=timezone.now)

    is_active = models.BooleanField(_('is waiting for matching'), default=False)
    is_pending = models.BooleanField(_('is waiting for confirmation'), default=False)
    is_confirmed = models.BooleanField(_('is confirmed'), default=False)

yurutomo/chatrooms/views.py
import json
import requests
from django.shortcuts import render
from django.utils import timezone
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Q
from django.http import QueryDict
from django.http.response import JsonResponse, HttpResponse
from django.views import generic
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy

from .models import Room, MatchingRecord, Topic

User = get_user_model()


class IndexView(generic.TemplateView):
    template_name = 'chatrooms/index.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class RoomMatchView(LoginRequiredMixin, generic.TemplateView):
    login_url = reverse_lazy('accounts:login')
    template_name = 'chatrooms/room_match.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class RoomView(LoginRequiredMixin, UserPassesTestMixin, generic.TemplateView):
    login_url = reverse_lazy('accounts:login')
    template_name = 'chatrooms/room.html'

    # Room に紐づいたユーザーのみアクセス可能にする
    def test_func(self):
        user = self.request.user
        room = get_object_or_404(Room, pk=self.kwargs['pk'])
        return any([user.pk == member.pk for member in room.users.all()])

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        room = get_object_or_404(Room, pk=self.kwargs['pk'])
        context['room'] = room

        members = room.users.all()

        member_names = {str(member.uuid): member.username for member in members}
        context['member_names'] = json.dumps(member_names)

        member_icons = {str(member.uuid): member.icon_image.url for member in members}
        context['member_icons'] = json.dumps(member_icons)

        return context

class RoomListView(generic.ListView):
    model = Room
    template_name = 'chatrooms/room_list.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['hoge'] = 'hoge'
        return context


# Skyway Test Page
def skyway(request):
    return render(request, 'chatrooms/skyway.html')


"""
検索API
"""
def popular_topics(request):
    params = request.GET

    # TODO
    # Topicにpopularityカラムを追加
    result = Topic.objects.all()
    return JsonResponse({"topics": [topic.data() for topic in result]}, status=200)


def search_topics(request):
    params = request.GET

    search_text = params.get('search_text')
    if search_text is None or not search_text:
        return JsonResponse({}, status=400)
    
    if search_text == '/all':
        # allコマンド = 全データ
        query = Q()
    else:
        keywords = search_text.split()

        query = Q()
        for keyword in keywords:
            query &= (
                Q(name__icontains=keyword)
                | Q(name__istartswith=keyword)
                | Q(name__iendswith=keyword)
                | Q(tags__name__icontains=keyword)
                | Q(tags__name__istartswith=keyword)
                | Q(tags__name__iendswith=keyword)
            )

    result = Topic.objects.filter(query)
    return JsonResponse({"topics": [topic.data() for topic in result]}, status=200)


"""
トピック追加API
"""
def create_topic(request):
    json_data = json.loads(request.body)

    name = json_data.get('name')
    topic, created = Topic.objects.update_or_create(
        name=name
    )
    if not created:
        return JsonResponse({'is_created': False, 'message': 'A topic with the same name already exists.'})
    topic.save()
    return JsonResponse({'is_created': True}, status=200)


"""
マッチング処理の WebAPI
Ajax で Json の送受信をすることを前提に書いている
"""

# マッチングに登録
@login_required
def register_matching(request):
    json_data = json.loads(request.body)
    user_id = request.user.pk


    condition = json_data.get('condition')
    if condition is None:
        return JsonResponse({}, status=400)
    
    # 条件のバリデーション
    topic = Topic.objects.get(name=condition['topic'])
    if topic is None:
        return JsonResponse({}, status=400)

    # 既に待ち状態であれば登録しない
    record = MatchingRecord.objects.filter(user=user_id, is_active=True).first()
    if record is not None:
        return JsonResponse({'is_registered': False}, status=200)
    
    submission_time = timezone.now()
    defaults = {
        'user': User.objects.get(pk=user_id),
        'topic': topic,
        'number': condition['number'],
        'submission_time': submission_time,
        'is_active': True,
        'is_pending': False,
        'is_confirmed': False
    }

    record, created = MatchingRecord.objects.update_or_create(
        user=User.objects.get(pk=user_id),
        defaults=defaults,
    )
    record.save()
    return JsonResponse({'is_registered': True}, status=200)


# マッチングを登録解除
@login_required
def unregister_matching(request):
    json_data = json.loads(request.body)
    user_id = request.user.pk

    # 解除するレコードがなければ処理しない
    record = MatchingRecord.objects.filter(user=user_id, is_active=True).first()
    if record is None:
        return JsonResponse({'is_unregistered': False}, status=200)

    record.is_active = False
    record.is_pending = False
    record.is_confirmed = False
    record.save()
    return JsonResponse({'is_unregistered': True}, status=200)



# マッチングしたルームIDを返す
@login_required
def get_match_room(request):
    user_id = request.user.pk

    myrecord = MatchingRecord.objects.filter(
        user=user_id,
        is_active=True,
        is_pending=False,
        is_confirmed=False).first()
    if myrecord is None:
        return JsonResponse({'message': 'valid record is not found.'}, status=404)

    # 入れるルームが既にあればそれを返す
    room = Room.objects.filter(
        users=user_id,
        is_active=True,
        created_date__gte=myrecord.submission_time).order_by('-created_date').first()
    if room is not None:
        # 保留状態にする
        myrecord.is_pending = True
        myrecord.save()
        return JsonResponse({
            'is_matched': True,
            'room_id': str(room.pk),
            'room_url': reverse_lazy('chatrooms:room', kwargs={'pk': room.pk})
            },
            status=200)

    """
    マッチングできるかチェック
    """
    # マッチングするものがあるか検索
    match_records = MatchingRecord.objects.filter(
        topic=myrecord.topic,
        number=myrecord.number,
        is_active=True,
        is_pending=False,
        is_confirmed=False).order_by('submission_time')

    # クエリセットが条件の数より少ない場合は不適
    if match_records.count() < myrecord.number:
        return JsonResponse({
            'is_matched': False,
            'message': 'not matched.'
            }, status=200)

    # クエリセットを条件の数に制限
    match_records = match_records[:myrecord.number]

    # クエリセットと関連した User を取得し、idをリスト match_users_id に格納
    match_users_id = [record.user.pk for record in match_records]

    # 自分が入っていない場合は不適
    if not user_id in match_users_id:
        return JsonResponse({
            'is_matched': False,
            'message': 'not matched.'
            }, status=200)


    """
    ルームを作成
    """
    # 既に作られているか
    room = Room.objects.filter(
        users=user_id,
        is_active=True,
        created_date__gte=myrecord.submission_time).order_by('-created_date').first()
    if room is None:
        # ない場合はルーム作成
        room = Room.objects.create(is_active=True)
        for user_id in match_users_id:
            room.users.add(User.objects.get(pk=user_id))
    
    
    # 保留状態にする
    myrecord.is_pending = True
    myrecord.save()
    
    return JsonResponse({
        'is_matched': True,
        'room_id': str(room.pk),
        'room_url': reverse_lazy('chatrooms:room', kwargs={'pk': room.pk})
        },
        status=200)


# マッチングを承認する
@login_required
def confirm_matching(request):
    json_data = json.loads(request.body)
    user_id = request.user.pk

    record = MatchingRecord.objects.filter(user=user_id, is_active=True, is_pending=True, is_confirmed=False).first()
    if record is None:
        return JsonResponse({'is_confirmed': False}, status=200)
    
    record.is_confirmed = True
    record.is_pending = False
    record.save()
    return JsonResponse({'is_confirmed': True}, status=200)

# マッチング承認をキャンセルして再び待ち状態へ
@login_required
def cancel_confirm(request):
    json_data = json.loads(request.body)
    user_id = request.user.pk

    record = MatchingRecord.objects.filter(user=user_id, is_active=True, is_pending=False, is_confirmed=True).first()
    if record is None:
        return JsonResponse({'is_cancelled': False}, status=200)
    
    record.is_pending = False
    record.is_confirmed = False
    record.save()
    return JsonResponse({'is_cancelled': True}, status=200)

# 他のユーザーがマッチングを承認したか
# 全員承認していればマッチング完了
@login_required
def get_match_completed(request):
    user_id = request.user.pk

    room_id = request.GET.get('room_id')
    if room_id is None or not room_id:
        return JsonResponse({
            'is_completed': False,
            'is_cancelled': False,
            'message': 'invalid room id.'
            }, status=400)
    
    room = Room.objects.filter(pk=room_id, users=user_id).first()
    if room is None:
        return JsonResponse({
            'is_completed': False,
            'is_cancelled': False,
            'message': 'invalid room id.'
            }, status=400)

    users = room.users.all()

    for user in users:
        try:
            record = MatchingRecord.objects.filter(user=user.pk).first()
        except User.matchingrecord.RelatedObjectDoesNotExist as ex:
            print('User.matchingrecord.RelatedObjectDoesNotExist')
            return JsonResponse({
                'is_completed': False,
                'is_cancelled': False,

yurutomo/chatrooms/templates/chatrooms/index.html
{% extends 'base.html' %}

{% block title %}ゆるとも｜気軽に話し相手を探そう！{% endblock %}

{% block content %}
<div uk-height-viewport="offset-top: true; offset-bottom: true"
    class="uk-section uk-section-small uk-flex uk-flex-middle uk-text-center uk-height-viewport"
    style="min-height: calc((100vh - 80px) - 102.5px);">
    <div class="uk-width-1-1">
        <div class="uk-container">
            <h2 class="uk-heading-medium">ゆるとも</h2>
            <p class="uk-margin-medium uk-text-lead">
                ゆるともは気軽に話し相手を探せる場所です！
            </p>
            <div uk-grid="" class="uk-child-width-auto uk-grid-medium uk-flex-inline uk-flex-center uk-grid">
                <div class="uk-first-column">
                    <a href="{% url 'chatrooms:room_match' %}" class="uk-button uk-button-primary uk-button-large">
                        はじめる
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

yurutomo/chatrooms/templates/chatrooms/room.html
{% extends 'base.html' %}
{% load static %}
{% load sass_tags %}

{% block css %}
<link rel="stylesheet" href="{% sass_src 'chatrooms/css/room.sass' %}">
{% endblock %}

{% block js %}

<!-- Vue.js 開発ver -->
<script src="https://cdn.jsdelivr.net/npm/vue@2.6.12/dist/vue.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vue-context-menu@2.0.6/vue-context-menu.min.js"></script>

<!-- Vue.js 本番環境ver バージョンを指定する -->
<!-- <script src="https://cdn.jsdelivr.net/npm/vue@2.6.12"></script> -->

<!-- Skyway SDK -->
<script src="https://cdn.webrtc.ecl.ntt.com/skyway-latest.js"></script>
{% endblock %}

{% block navbar %}
<!-- Navbar は使わない -->
{% endblock %}

{% block content %}
<div id="room" class="wrapper">
    <div class="main">
        <div class="tools-container">
            <div class="tool" id="leave-room">
                <button class="tool-btn" id="leave-room-btn" @click="leaveRoom">
                    退室 <i class="fas fa-door-open"></i>
                </button>
            </div>

            <div class="tool" id="mic">
                <button class="tool-btn icon-btn-container" id="mic-btn" @click="switchMute(localStream)">
                    <i v-if="localStream.isMuted" class="fas fa-microphone-slash fa-2x icon-btn" id="icon-off-mic"></i>
                    <i v-else class="fas fa-microphone fa-2x icon-btn" id="icon-on-mic"></i>
                </button>
            </div>

            <div class="tool" id="settings">
                <button class="tool-btn icon-btn-container" id="settings-btn" uk-toggle="target: #modal-settings">
                    <i class="fas fa-cog fa-2x icon-btn"></i>
                </button>

                <!-- ↓↓↓ Modal ↓↓↓ -->
                <div id="modal-settings" uk-modal>
                    <div id="select-audio" class="uk-modal-dialog uk-modal-body" uk-overflow-auto>
                        <button class="uk-modal-close-default" type="button" uk-close></button>
                        <h3 class="uk-modal-title">設定</h3>

                        <ul class="uk-list uk-list-square">
                            <li>
                                <div>
                                    <h5>マイク</h5>
                                    <select v-model="selectedAudio" @change="onDeviceChange">
                                        <option disabled value=""></option>
                                        <option v-for="(audio, i) in audios" :key="i" :value="audio.deviceId">
                                            [[audio.label]]
                                        </option>
                                    </select>
                                </div>
                            </li>
                            <!-- <li>
                                <div>
                                    <h5>Video Input</h5>
                                    <select v-model="selectedVideo" @change="onDeviceChange">
                                        <option disabled value="">Video Input</option>
                                        <option v-for="(video, i) in videos" :key="i" :value="video.deviceId">
                                            [[video.label]]
                                        </option>
                                    </select>
                                </div>
                            </li> -->
                        </ul>
                    </div>
                </div>
                <!-- ↑↑↑ Modal ↑↑↑ -->

            </div>





        </div>


        <div class="chat-content">

            <div class="messages-container" :style="{height: messageHeight}">
                <div id="messages" class="messages">
                    <div class="message-container" v-for="message in messages">
                        <div class="message" v-if="message.type=='message'">
                            <div class="message-icon">
                                <img :src="memberIcons[message.srcUserId]" class="message-icon-img">
                            </div>
                            <div class="message-body">
                                <span class="message-user">[[message.srcUser]]</span>
                                <div class="message-data">[[message.data]]</div>
                            </div>
                        </div>
                        <div class="message" v-else-if="message.type=='log'">
                            <div class="message-body">
                                <div class="message-data">[[message.data]]</div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <div class="textarea-container">
                <div class="text-box dark-scrollbar">
                    <div class="textarea-box">
                        <div class="text-dummy" aria-hidden="true">[[myText + "\u200b"]]</div>
                        <textarea class="textarea scroll-none" id="my-text" v-model="myText"
                            @keydown.enter.shift.exact.prevent="sendMessage" placeholder="Message"></textarea>
                    </div>
                    <div class="text-btn-container">
                        <button id="send-btn" class="text-btn icon-btn-container" @click="sendMessage">
                            <i class="fas fa-paper-plane fa-2x icon-btn"></i>
                        </button>
                    </div>
                </div>


            </div>
        </div>
    </div>

    <div class="sub">
        <div class="streams-container">
            <div class="streams">
                <div class="stream local-stream">
                    <audio id="my-video" autoplay playsinline :src-object.prop="localStream.stream"></audio>
                    <div class="uk-margin-xsmall">
                        <img src="{{user.icon_image.url}}" class="stream-img local-stream-img"
                            :class="{'stream-on-sound' : localStream.onSound}">
                    </div>
                    <!-- 環境によって srcObject.prop と src-object.prop のどちらかで動く模様 -->
                    <!-- <video id="my-video" width="400px" autoplay muted playsinline :srcObject.prop="localStream"></video> -->
                    <div class="stream-name uk-margin-xsmall">[[ truncateName("{{ user.username }}") ]]
                    </div>
                </div>

                <div class="stream remote-stream" v-for="(stream, id) in streams"
                    @contextmenu.prevent="$refs.ctx.open($event, {id: id, isMuted: stream.isMuted})">
                    <audio autoplay playsinline :src-object.prop="stream.stream"></audio>
                    <div>
                        <img :src="memberIcons[id]" class="stream-img remote-stream-img"
                            :class="{'stream-on-sound': stream.onSound}">
                    </div>
                    <div class="stream-name">[[ memberNames[id] ]]</div>
                </div>
                <context-menu ref="ctx" @ctx-open="onCtxOpen">
                    <li class="ctx-item" v-if="ctxDatas.isMuted" @click="switchMute(streams[ctxDatas.id])">ミュート解除</li>
                    <li class="ctx-item" v-else @click="switchMute(streams[ctxDatas.id])">ミュート</li>
                </context-menu>
                <!-- <button @click="getLog">Log</button> -->
            </div>
        </div>
    </div>

</div>

<script type="text/javascript">
    const userId = "{{user.uuid}}";
    const roomId = "{{room.uuid}}";
    const memberNames = JSON.parse("{{member_names}}".replace(/&quot;/g, "\""));
    const memberIcons = JSON.parse("{{member_icons}}".replace(/&quot;/g, "\""));
    const indexUrl = "{% url 'chatrooms:index' %}";
</script>
<script type="text/javascript" src="{% static 'chatrooms/js/room.js' %}"></script>


{% endblock %}

yurutomo/chatrooms/templates/chatrooms/room_list.html
{% extends 'base.html' %}

{% block content %}

<ul>
{% for room in object_list %}
<li>{{ room.uuid }} - {{ room.created_date|date }}</li>
{% empty %}
<li>No rooms yet.</li>
{% endfor %}
</ul>
{% endblock %}

yurutomo/chatrooms/templates/chatrooms/room_match.html
{% extends 'base.html' %}
{% load static %}
{% load sass_tags %}

{% block css %}
<link rel="stylesheet" href="{% sass_src 'chatrooms/css/room_match.sass' %}">

{% endblock %}

{% block js %}
<!-- Vue.js 開発ver -->
<script src="https://cdn.jsdelivr.net/npm/vue@2.6.12/dist/vue.js"></script>

<!-- Vue.js 本番環境ver バージョンを指定する -->
<!-- <script src="https://cdn.jsdelivr.net/npm/vue@2.6.12"></script> -->

<!-- Axios -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.15.2/axios.js"></script>
{% endblock %}


{% block content %}
<div class="uk-container uk-margin-large-top">
    <div class="uk-flex uk-flex-center">
        <p class="uk-text-large">トピックを選んでマッチングしましょう！</p>
    </div>

    <div id="room-match" class="uk-margin-top" v-cloak>
        <div id="matching-btn-form" class="uk-margin">
            <div class="uk-flex uk-flex-center uk-height-xsmall">
                <div id="matching-message" class="uk-margin"> &nbsp; [[matchingMessageText]]</div>
            </div>

            <div class="uk-flex uk-flex-center uk-height-xsmall">

                <div id="matching-div" v-show="showMatching">
                    <button id="start-btn" class="matching-btn" :disabled="btnDisable" v-on:click="start">マッチング</button>
                </div>
                <div id="matching-div" v-show="showWaiting">
                    <span id="waiting-message" class=""> <button id="quit-btn" class="matching-btn"
                            v-on:click="quit">×</button> Waiting...</span>

                </div>

                <div id="confirm-div" v-show="showConfirm">
                    <button id="confirm-btn" class="matching-btn"
                        v-on:click="confirm(); clearDisplayTimer()">入室</button>
                    <button id="cancel-btn" class="matching-btn"
                        v-on:click="cancel(); clearDisplayTimer()">キャンセル</button>
                    <div id="life-bar" class="uk-margin">
                        <progress id="life-progressbar" class="uk-progress" value="100" max="100"></progress>
                    </div>
                </div>

            </div>
        </div>

        <div id="topic-form" class="uk-margin-large-top">
            <div v-if="topic">
                <div class="uk-flex uk-flex-center uk-child-width-1-2@s uk-child-width-1-3@m">
                    <div class="uk-card uk-card-default topic-card selected-topic-card">
                        <div class="topic-body">
                            [[topic]]
                        </div>
                        <button id="cancel-topic" v-if="!isMatching" @click="topic=''" type="button"
                            uk-icon="icon: close"></button>
                    </div>
                </div>

            </div>
            <div v-else>
                <div class="uk-margin uk-flex uk-flex-center">
                    <div class="uk-inline uk-width-1-2">
                        <button class="uk-form-icon uk-form-icon-flip" @click="searchTopics" uk-icon="icon: search"
                            style="outline: none;"></button>
                        <input class="uk-input" v-model="searchText" @keydown.enter="searchTopics" type="text"
                            placeholder="トピック">
                    </div>
                </div>
                <div class="uk-margin" v-if="searchResult.length">
                    <div class="uk-margin">
                        <h3>
                            検索結果
                        </h3>
                    </div>
                    <div class="uk-child-width-1-2@s uk-child-width-1-3@m uk-grid-match" uk-grid>
                        <div v-for="(result, id) in searchResult">
                            <button class="uk-card uk-card-default topic-card" @click="setTopic(result.name)">
                                <div class="topic-body">
                                    [[ cleanTopicName(result.name) ]]
                                </div>
                            </button>
                        </div>
                    </div>

                    <div class="uk-margin-large">
                        <hr>
                    </div>
                </div>
                <div>
                    <div class="uk-margin">
                        <h3>
                            トピック　<a href="#topic-add-modal" uk-icon="plus-circle" uk-toggle
                                uk-tooltip="新しいトピックを追加しよう"></a>
                        </h3>
                    </div>

                    <div id="topic-add-modal" class="modal" uk-modal>
                        <div class="uk-modal-dialog uk-modal-body">
                            <button class="uk-modal-close-default" type="button" uk-close></button>
                            <h2 class="uk-modal-title">トピックの追加</h2>
                            <div class="uk-flex uk-flex-center">
                                <input v-model="newTopic" class="uk-input uk-form-width-large" type="text"
                                    placeholder="追加したいトピック">
                            </div>
                            <p>
                                [[ newTopicError ]]
                            </p>
                            <p class="uk-text-right">
                                <button class="uk-button uk-button-primary" type="button"
                                    v-on:click="createTopic">決定</button>
                            </p>
                        </div>
                    </div>

                    <div class="uk-child-width-1-2@s uk-child-width-1-3@m uk-grid-match" uk-grid>
                        <div v-for="(result, id) in popularTopics">
                            <button class="uk-card uk-card-default topic-card" @click="setTopic(result.name)">
                                <div class="topic-body">
                                    [[cleanTopicName(result.name) ]]
                                </div>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <div id="number-form" class="uk-margin">
            <div v-if="topic">
                <div class="uk-flex uk-flex-center">
                    <div class="uk-flex uk-flex-column">
                        <div v-if="isMatching">
                            <div class="uk-text-center">
                                [[ number ]]人マッチング
                            </div>
                        </div>
                        <div v-else>
                            <div class="">
                                何人でマッチングしますか？
                            </div>
                            <div class="uk-flex uk-flex-center uk-margin-small">
                                <select class="uk-select uk-width-small" v-model="number" :hidden="isMatching">
                                    <option hidden value="0" selected style="text-align: center;">人数</option>
                                    <option v-for="n of numberLimit" :key="n" :value="n" style="text-align: center;">
                                        [[n]]
                                    </option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <ul id="list-message"></ul>
</div>

{% csrf_token %}
<script type="text/javascript">
    const popularTopicsUrl = "{% url 'chatrooms:popular_topics' %}"
    const searchTopicsUrl = "{% url 'chatrooms:search_topics' %}"
    const createTopicUrl = "{% url 'chatrooms:create_topic' %}"

    const registerUrl = "{% url 'chatrooms:register_matching' %}";
    const unregisterUrl = "{% url 'chatrooms:unregister_matching' %}";
    const getMatchRoomUrl = "{% url 'chatrooms:get_match_room' %}";
    const confirmUrl = "{% url 'chatrooms:confirm_matching' %}";
    const cancelUrl = "{% url 'chatrooms:cancel_confirm' %}";
    const isCompletedUrl = "{% url 'chatrooms:get_match_completed' %}";
</script>
<script type="text/javascript" src="{% static 'chatrooms/js/room_match.js' %}"></script>

{% endblock %}