yurutomo/accounts/urls.py
# from django.contrib import admin
from django.urls import path


from . import views


app_name = 'accounts'


urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('guestlogin/', views.GuestLogin.as_view(), name='guest_login'),
    path('settings/<uuid:pk>', views.ChangeSettingsView.as_view(), name='settings'),
    path('profile/<uuid:pk>', views.ProfileUpdateView.as_view(), name='profile_settings'),
]

yurutomo/chatrooms/urls.py
from django.urls import path

from . import views

app_name= 'chatrooms'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('room-match', views.RoomMatchView.as_view(), name='room_match'),
    path('room/<uuid:pk>', views.RoomView.as_view(), name='room'),
    path('skyway', views.skyway, name='skyway'),
    path('rooms', views.RoomListView.as_view(), name='room_list'),

    path('api/populartopics', views.popular_topics, name='popular_topics'),
    path('api/searchtopics', views.search_topics, name='search_topics'),
    path('api/createtopic', views.create_topic, name='create_topic'),

    path('api/registermatching', views.register_matching, name='register_matching'),
    path('api/unregistermatching', views.unregister_matching, name='unregister_matching'),
    path('api/getmatchroom', views.get_match_room, name='get_match_room'),
    path('api/confirmmatching', views.confirm_matching, name='confirm_matching'),
    path('api/cancelconfirm', views.cancel_confirm, name='cancel_confirm'),
    path('api/getmatchcompleted', views.get_match_completed, name='get_match_completed'),
]

yurutomo/yurutomo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# adminsite のサイドバーを無効にする
admin.site.enable_nav_sidebar = False

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chatrooms.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

yurutomo/templates/base.html
{% load static %}
{% load sass_tags %}

<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}ゆるとも｜気軽に話し相手を探そう！{% endblock %}</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css"
        integrity="sha384-Bfad6CLCknfcloXFOyFnlgtENryhrpZCe29RTifKEixXQZ38WheV+i/6YWSzkz3V" crossorigin="anonymous">
    <!-- UIkit CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/uikit@3.6.17/dist/css/uikit.min.css" />

    <link rel="stylesheet" href="{% sass_src 'chatrooms/css/common.sass' %}">
    <!-- データバインディング完了まで要素の描画を遅らせる -->
    <style>
        [v-cloak] {
            display: none;
        }
    </style>
    {% block css %}{% endblock %}

    <!-- UIkit JS -->
    <script src="https://cdn.jsdelivr.net/npm/uikit@3.6.17/dist/js/uikit.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/uikit@3.6.17/dist/js/uikit-icons.min.js"></script>
    {% block js %}{% endblock %}

</head>

<body>
    {% block navbar %}
    <div uk-sticky="sel-target: .uk-navbar-container; cls-active: uk-navbar-sticky;">
        <nav class="uk-navbar-container" style="position: relative; z-index: 980; background-color: #464646;">
            <div class="uk-container uk-container-expand">
                <div uk-navbar>
                    <div class="uk-navbar-left">

                        <ul class="uk-navbar-nav">
                            <li class="uk-active"><a href="{% url 'chatrooms:index' %}" style="color: white;">HOME</a></li>

                        </ul>

                    </div>
                    <div class="uk-navbar-right">
                        <ul class="uk-navbar-nav">
                            {% if user.is_authenticated %}
                            <li>
                                <a href="#">
                                    <img src="{{user.icon_image.url}}"
                                        style="width: 40px; height: 40px; border-radius: 50%;">
                                </a>
                                <div class="uk-navbar-dropdown">
                                    <ul class="uk-nav uk-navbar-dropdown-nav">
                                        <li class="uk-active">
                                            <h5>{{user.username}}</h5>
                                        </li>
                                        <li class="uk-nav-divider"></li>
                                        {% if not user.is_guest %}
                                        <li><a href="{% url 'accounts:profile_settings' pk=user.pk %}">プロフィール</a></li>
                                        {% endif %}
                                        <li><a href="{% url 'logout' %}">ログアウト</a></li>
                                    </ul>
                                </div>
                            </li>
                            {% else %}
                            <li>
                                <a href="{% url 'accounts:signup' %}">新規登録</a>
                            </li>
                            <li>
                                <a href="{% url 'login' %}">ログイン</a>
                            </li>
                            {% endif %}
                        </ul>

                    </div>
                </div>
            </div>
        </nav>
    </div>
    {% endblock %}
    {% block content %}{% endblock %}
    {% if messages %}
    <div class="uk-width-1-1 uk-flex uk-flex-left" style="position:fixed; bottom:0;">
        <div class="uk-flex uk-flex-column">
            <ul class="uk-list">
                {% for message in messages %}
                <div class="uk-width-large uk-margin-remove {% if message.tags %} uk-alert-{{ message.tags }} {% endif %}"
                    uk-alert>
                    <a class="uk-alert-close" uk-close></a>
                    <p>{{ message }}</p>
                </div>
                {% endfor %}
            </ul>
        </div>
    </div>
    {% endif %}

</body>

</html>